
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.unbosque.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PERSON_ROLE = 14;
  public static final int TACTICA = 5;
  public static final int STRING_ATTRIBUTES = 16;
  public static final int ASIGNATION_TOKEN = 17;
  public static final int SEMICOLON = 18;
  public static final int JUEGO_LIBRE = 6;
  public static final int TEAM = 12;
  public static final int REPETITIONS = 11;
  public static final int COLON = 19;
  public static final int PLAN_ENTRENAMIENTO = 2;
  public static final int PERSON_ATTRIBUTES = 15;
  public static final int PERSONA = 8;
  public static final int COMMA = 20;
  public static final int ASIGNACION = 9;
  public static final int PERSON_ID = 10;
  public static final int PASS_CONDITION = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ACTIVITY = 7;
  public static final int ENTRENAMIENTO = 3;
  public static final int CALENTAMIENTO = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLAN_ENTRENAMIENTO",
  "ENTRENAMIENTO",
  "CALENTAMIENTO",
  "TACTICA",
  "JUEGO_LIBRE",
  "ACTIVITY",
  "PERSONA",
  "ASIGNACION",
  "PERSON_ID",
  "REPETITIONS",
  "TEAM",
  "PASS_CONDITION",
  "PERSON_ROLE",
  "PERSON_ATTRIBUTES",
  "STRING_ATTRIBUTES",
  "ASIGNATION_TOKEN",
  "SEMICOLON",
  "COLON",
  "COMMA"
  };
}

